### PR TITLE
docs: add commits convention description in contributing/readme.md

### PR DESCRIPTION
**Pull request by paul1319**
Towards https://github.com/googleapis/google-cloud-python/issues/9897

### CODE REVIEW

**Comment by paul1319** [comment]
@IlyaFaer

**Comment by tswast** [comment]
Let's link to https://github.com/angular/angular/blob/master/CONTRIBUTING.md#type also, since it has the full set of commit types we support.

**Comment by tswast** [comment]
Hmm... Except I don't see `chore` in there. @bcoe Do you have a better list of conventional commit types we use?

**Comment by crwilcox** [comment]
I don't know if it was added, but I see it 

```
types other than fix: and feat: are allowed, for example @commitlint/config-conventional (based on the the Angular convention) recommends build:, chore:, ci:, docs:, style:, refactor:, perf:, test:, and others.

```

**Comment by bcoe** [comment]
@tswast @crwilcox I'm open to edits on conventionalcommits.org, which I help edit.

The motivation of the specification was to be slightly less prescriptive about the types that folks use, as the angular conventions were slightly more tailored to the angular project itself.

When I explain the specification to folks, I point out that the most important types are:

* `fix`: when you're fixing something.
* `feat`: when you're adding a feature.
* and an `!` point when you're breaking something (this was not part of the original angular specification, but is an important improvement to the specification in my opinion; folks kept forgetting to add `Breaking Change`, or typoing it, which would break our automation.

**Pull request merged**
