### PR TITLE
Remove Firestore conformance tests

### PR DESCRIPTION
**Pull request by BenWhitehead**
Firestore conformance tests are being migrated to the
googleapis/conformance-tests repo.

### CODE REVIEW

**Comment by BenWhitehead** [comment]
@jadekler Please review

**Comment by BenWhitehead** [comment]
PR importing deleted files to https://github.com/googleapis/conformance-tests/pull/9

**Comment by BenWhitehead** [comment]
@jadekler Can you merge this (I don't have write permissions)?

**Comment by jadekler** [comment]
Sorry - yes certainly!

**Comment by BenWhitehead** [comment]
Great, thank you!

**Pull request merged**
